🚀 Release/1.2.0
skoruba/Duende.IdentityServer.Admin pull request #56
Opened 2022-02-25 17:08 UTC by skoruba

# 🚀 Release/1.2.0
 
- Should the docker-compose.vs.*.yml reference .NET 6? - #54 
- Management for Identity Providers - #52

2022-03-02 16:54 UTC, hoba84 requested changes
Some review comments in exception handling (error scenarios) and EN, DE translation.

2022-03-02 16:54 UTC, hoba84 commented on src/Skoruba.Duende.IdentityServer.Admin.UI/Resources/Areas/AdminUI/Views/IdentityProvider/IdentityProviderDelete.de.resx
> +    <value>Identitäts-Provider löschen</value>
Wrong translation, change to "Identitätsanbieter löschen"

2022-03-02 16:54 UTC, hoba84 commented on src/Skoruba.Duende.IdentityServer.Admin.UI/Resources/Areas/AdminUI/Views/IdentityProvider/IdentityProviderDelete.de.resx
> +    <value>Identitäts-Provider löschen</value>
Wrong translation, change to "Identitätsanbieter löschen"

2022-03-02 16:54 UTC, hoba84 commented on src/Skoruba.Duende.IdentityServer.Admin.UI/Resources/Areas/AdminUI/Views/Shared/_Layout.de.resx
>      <value>Logout</value>
Wrong translation, change to "Abmelden"

2022-03-02 16:54 UTC, hoba84 commented on src/Skoruba.Duende.IdentityServer.Admin.UI/Resources/Areas/AdminUI/Views/Shared/_Layout.de.resx
> +    <value>Identity Providers</value>
Wrong translation, change to "Identitätsanbieter"

2022-03-02 16:54 UTC, hoba84 commented on src/Skoruba.Duende.IdentityServer.Admin.UI/Resources/Areas/AdminUI/Views/Shared/_Layout.de.resx
>      <value>Identitäts-Ressources</value>
Wrong translation, change to "Identitätsresourcen"

2022-03-02 19:32 UTC, skoruba commented on src/Skoruba.Duende.IdentityServer.Admin.Api/Controllers/IdentityProvidersController.cs
> +            await _identityProviderService.GetIdentityProviderAsync(identityProvider.Id);
There are validations in the Get method, if the ID exists.

2022-03-02 19:35 UTC, skoruba commented
@hoba84 - thank you for your great feedback, can you please send a PR to this branch [release/1.2.0](https://github.com/skoruba/Duende.IdentityServer.Admin/tree/release/1.2.0) with your fixes regarding to translations etc? It would help a lot. Thanks!

2022-04-16 11:54 UTC, rpbrongers commented on src/Skoruba.Duende.IdentityServer.Admin.BusinessLogic/Services/IdentityProviderService.cs
> +            await AuditEventLogger.LogEventAsync(new IdentityProviderAddedEvent(identityProvider));
The code follows the exact pattern of all the other services- I figured we don't want to just have one deviating from all the others. So perhaps we should 'upgrade' the comment to a backlog item that applies to the entire code base, not just this file.

2022-04-16 11:54 UTC, rpbrongers commented on src/Skoruba.Duende.IdentityServer.Admin.Api/Controllers/IdentityProvidersController.cs
> +            await _identityProviderService.GetIdentityProviderAsync(identityProvider.Id);
The code follows the exact pattern of all the other controllers - I figured we don't want to just have one deviating from all the others. So perhaps we should 'upgrade' the comment to a backlog item that applies to the entire code base, not just this file.

2022-04-16 11:54 UTC, rpbrongers commented on src/Skoruba.Duende.IdentityServer.Admin.UI/Areas/AdminUI/Controllers/IdentityProviderController.cs
> +                        ModelState.AddModelError($"{nameof(IdentityProviderDto.Properties)}[{d.Key}].{nameof(IdentityProviderPropertyDto.Name)}", $"duplicate name ({d.Value.Name})");
Why? No other model validation errors do that.

2022-04-16 11:55 UTC, rpbrongers commented on src/Skoruba.Duende.IdentityServer.Admin.EntityFramework/Repositories/IdentityProviderRepository.cs
> +            DbContext.IdentityProviders.Remove(identityProviderToDelete);
The code follows the exact pattern of all the other repositories - I figured we don't want to just have one deviating from all the others. So perhaps we should 'upgrade' the comment to a backlog item that applies to the entire code base, not just this file.

2022-08-04 18:33 UTC, closed without merging